theme: jekyll-theme-minimal
title: IDC402 Term Project
subtitle: Modelling Complex Systems
description: Modelling a Predator Prey model using a CA framework
show_downloads: true
github:
  owner_url: https://aaevelion.github.io/